# keywords.py
# Expanded dataset for waste sorting including hazardous materials

# Keyword -> Category
keyword_map = {
    # Recyclable
    "bottle": "recyclable",
    "plastic": "recyclable",
    "glass": "recyclable",
    "cd": "recyclable",
    "paper": "recyclable",
    "can": "recyclable",
    "cardboard": "recyclable",
    "jar": "recyclable",
    "newspaper": "recyclable",
    "magazine": "recyclable",
    "tin": "recyclable",
    "aluminum": "recyclable",
    "metal": "recyclable",
    "book": "recyclable",
    "envelope": "recyclable",
    "carton": "recyclable",
    "plastic bottle": "recyclable",
    "glass bottle": "recyclable",
    "milk carton": "recyclable",
    "juice carton": "recyclable",
    "aerosol can": "recyclable",
    "paperboard": "recyclable",
    "junk mail": "recyclable",
    "office paper": "recyclable",
    "printer paper": "recyclable",
    "folder": "recyclable",
    "cereal box": "recyclable",
    "shoebox": "recyclable",
    "metal lid": "recyclable",
    "aluminum foil": "recyclable",
    "steel can": "recyclable",
    "soda can": "recyclable",
    "beer can": "recyclable",
    "wine bottle": "recyclable",
    "beer bottle": "recyclable",
    "glass jar": "recyclable",

    # Compostable
    "food": "compostable",
    "banana": "compostable",
    "apple": "compostable",
    "orange": "compostable",
    "vegetable": "compostable",
    "fruit": "compostable",
    "leaves": "compostable",
    "grass": "compostable",
    "plant": "compostable",
    "coffee": "compostable",
    "tea": "compostable",
    "egg shell": "compostable",
    "peel": "compostable",
    "bread": "compostable",
    "rice": "compostable",
    "pasta": "compostable",
    "nutshell": "compostable",
    "flower": "compostable",
    "yard waste": "compostable",
    "leftovers": "compostable",
    "potato": "compostable",
    "tomato": "compostable",
    "onion": "compostable",
    "garlic": "compostable",
    "carrot": "compostable",
    "lettuce": "compostable",
    "spinach": "compostable",
    "cabbage": "compostable",
    "melon": "compostable",
    "peach": "compostable",
    "pear": "compostable",
    "plum": "compostable",
    "grape": "compostable",
    "strawberry": "compostable",
    "blueberry": "compostable",
    "avocado": "compostable",
    "corn": "compostable",
    "pumpkin": "compostable",
    "zucchini": "compostable",
    "eggplant": "compostable",
    "lemon": "compostable",

    # Trash
    "chip": "trash",
    "wrapper": "trash",
    "styrofoam": "trash",
    "diaper": "trash",
    "cigarette": "trash",
    "plastic bag": "trash",
    "toothbrush": "trash",
    "foam": "trash",
    "napkin": "trash",
    "tissue": "trash",
    "mirror": "trash",
    "ceramic": "trash",
    "broken glass": "trash",
    "clothing": "trash",
    "rubber": "trash",
    "styrofoam cup": "trash",
    "plastic straw": "trash",
    "plastic spoon": "trash",
    "plastic fork": "trash",
    "plastic knife": "trash",
    "takeout container": "trash",
    "chip bag": "trash",
    "candy wrapper": "trash",
    "toothpaste tube": "trash",
    "shampoo bottle": "trash",
    "conditioner bottle": "trash",
    "perfume bottle": "trash",
    "makeup container": "trash",
    "shoe": "trash",
    "sock": "trash",
    "broken toy": "trash",
    "styrofoam plate": "trash",
    "plastic wrap": "trash",
    "bubble wrap": "trash",
    "polystyrene": "trash",
    "paint tube": "trash",
    "used mask": "trash",
    "sanitary pad": "trash",
    "razor": "trash",

    # Hazardous
    "battery": "hazardous",
    "electronics": "hazardous",
    "light bulb": "hazardous",
    "thermometer": "hazardous",
    "fluorescent tube": "hazardous",
    "paint": "hazardous",
    "solvent": "hazardous",
    "pesticide": "hazardous",
    "chemical": "hazardous",
    "aerosol spray": "hazardous",
}
